/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import { connectionConfigVar } from "@prismatic-io/spectral/dist/integration";
import {
  findUserDefinedComponentKey,
  requireIntegrationContext,
} from "@prismatic-io/spectral/dist/serverTypes";
import type {
  ConfigVarExpression,
  ConfigVarVisibility,
} from "@prismatic-io/spectral/dist/types";

export interface ApiKeyValues {
  /**
   * Base URL
   *
   * @default https:\/\/taekwondo-relapsing-backlash.ngrok-free.dev\/api
   */
  baseUrl?: string;
  /**
   * API Key
   *
   */
  apiKey: string;
}

/**
 * ShipHawk Connection
 *
 * @comments Connect to ShipHawk API using an API key
 * This object is used to support type hinting.
 */
export const apiKey = {
  key: "apiKey",
  perform: (_values: ApiKeyValues): Promise<void> => Promise.resolve(),
  inputs: {
    baseUrl: {
      inputType: "string",
      collection: undefined,
      default: `https:\/\/taekwondo-relapsing-backlash.ngrok-free.dev\/api`,
    },
    apiKey: {
      inputType: "password",
      collection: undefined,
      default: ``,
      required: true,
    },
  },
} as const;

/**
 * ShipHawk Connection Connection Helper
 *
 * @comments This wrapper function can be used directly in config wizard definitions.
 */
export const shiphawkApiKey = (
  stableKey: string,
  values: {
    baseUrl?: (
      | {
          value: string;
        }
      | ConfigVarExpression
    ) &
      ConfigVarVisibility & { writeOnly?: true };
    apiKey: (
      | {
          value: string;
        }
      | ConfigVarExpression
    ) &
      ConfigVarVisibility & { writeOnly?: true };
  },
) => {
  return connectionConfigVar({
    dataType: "connection",
    stableKey,
    connection: {
      get component() {
        const context = requireIntegrationContext();
        return findUserDefinedComponentKey(
          "shiphawk",
          false,
          context.componentRegistry,
        );
      },
      key: "apiKey",
      values,
    },
  });
};
