/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import { ConfigVarExpression } from "@prismatic-io/spectral";
import {
  findUserDefinedComponentKey,
  requireIntegrationContext,
} from "@prismatic-io/spectral/dist/serverTypes";
import type { Connection } from "@prismatic-io/spectral/dist/types";

export interface PollForChangesValues {
  /**
   * ShipHawk Connection
   *
   */
  connection: Connection;
}

/**
 * Poll for new or updated shipments on a schedule
 *
 * @description Poll for new or updated shipments on a schedule
 * This object is used to support type hinting.
 */
export const pollForChanges = {
  key: "pollForChanges",
  perform: <TReturn,>(_values: PollForChangesValues): Promise<TReturn> =>
    Promise.resolve<TReturn>({} as TReturn),
  inputs: {
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
  },
} as const;

/**
 * Poll for new or updated shipments on a schedule Trigger Helper
 *
 * @comments This wrapper function can be used directly in flow definitions.
 */
export const shiphawkPollForChanges = (values: {
  connection:
    | {
        value: Connection;
      }
    | ConfigVarExpression;
}) => {
  return {
    get component() {
      const context = requireIntegrationContext();
      return findUserDefinedComponentKey(
        "shiphawk",
        false,
        context.componentRegistry,
      );
    },
    key: "pollForChanges",
    values,
  } as const;
};
