/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface DeleteItemValues {
  /**
   * ShipHawk Connection
   *
   */
  connection: Connection;
  /**
   * Item ID
   *
   */
  itemId: string;
}

/**
 * Delete Shipment
 *
 * @description Delete a shipment by ID
 */
export const deleteItem = {
  key: "deleteItem",
  perform: async <TReturn,>(values: DeleteItemValues): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.shiphawk.deleteItem({
      ...values,
    })) as TReturn;
  },
  inputs: {
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
    itemId: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
  },
  examplePayload: {},
} as const;
