/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface ListItemsValues {
  /**
   * ShipHawk Connection
   *
   */
  connection: Connection;
}

/**
 * List Shipments
 *
 * @description List all shipments
 */
export const listItems = {
  key: "listItems",
  perform: async <TReturn,>(values: ListItemsValues): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.shiphawk.listItems({
      ...values,
    })) as TReturn;
  },
  inputs: {
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
  },
  examplePayload: {},
} as const;
