/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import type { Connection } from "@prismatic-io/spectral/dist/types";
import { requireContext } from "@prismatic-io/spectral/dist/serverTypes";

export interface UpdateItemValues {
  /**
   * ShipHawk Connection
   *
   */
  connection: Connection;
  /**
   * Item ID
   *
   */
  itemId: string;
  /**
   * Tracking Number
   *
   */
  trackingNumber: string;
  /**
   * Origin
   *
   */
  origin: string;
  /**
   * Destination
   *
   */
  destination: string;
  /**
   * Carrier
   *
   */
  carrier?: string;
  /**
   * Estimated Delivery
   *
   */
  estimatedDelivery?: string;
  /**
   * Status
   *
   */
  status: string;
}

/**
 * Update Shipment
 *
 * @description Update an existing shipment
 */
export const updateItem = {
  key: "updateItem",
  perform: async <TReturn,>(values: UpdateItemValues): Promise<TReturn> => {
    const context = requireContext();
    return (await context.components.shiphawk.updateItem({
      ...values,
    })) as TReturn;
  },
  inputs: {
    connection: {
      inputType: "connection",
      collection: undefined,
      default: `null`,
      required: true,
    },
    itemId: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    trackingNumber: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    origin: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    destination: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
    carrier: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    estimatedDelivery: {
      inputType: "string",
      collection: undefined,
      default: ``,
    },
    status: {
      inputType: "string",
      collection: undefined,
      default: ``,
      required: true,
    },
  },
  examplePayload: {},
} as const;
