/**
 * This file was automatically generated by spectral.
 * Any changes made will be overwritten.
 */
import actions from "./actions";
import connections from "./connections";
import dataSources from "./dataSources";
import triggers from "./triggers";

export { actions, connections, dataSources, triggers };

export default {
  key: "shiphawk",
  public: false,
  signature: "818708e716b28d05fcb5b84e67c4fa39710f58c4",
  actions,
  dataSources,
  connections,
  triggers,
} as const;
